import { createSlice } from '@reduxjs/toolkit';

// Create a Redux slice for the tasks feature
const tasksSlice = createSlice({
    name: 'tasks',  // Name of the slice
    initialState: [], // Initial state for the tasks feature
    reducers: {
          // Define actions and their associated reducers
        loadTasks: (state, action) => {
            return action.payload;
        },
        // Define actions and their associated reducers
        addTask: (state, action) => {
            // This reducer handles adding a new task to the state
            state.push(action.payload);
        },
        deleteTask: (state, action) => {
            // This reducer handles deleting a task from the state
            return state.filter((task) => task.id !== action.payload);
        },
    },
});
// Export the actions generated by createSlice
export const { loadTasks, addTask, deleteTask } = tasksSlice.actions;
// Export the reducer that is created with createSlice()
export default tasksSlice.reducer;
